---
# Test for CVE-2019-3462 (see https://justi.cz/security/2019/01/22/apt-rce.html)
# If apt < 1.4.9, it is vulnerable to CVE-2019-3462 and we must ensure no
# redirects are followed when updating apt via apt.
- name: Get apt version
  shell: dpkg-query --showformat='${Version}' --show apt
  register: _apt_query_command_output_result
  changed_when: false
  tags:
    - apt

- name: Verify that the version of apt installed is not vulnerable to 2019-3462 (Xenial)
  assert:
    that: _apt_query_command_output_result.stdout is version('1.2.29ubuntu0.1', '>=')
  tags:
    - apt
