---
# Destination directory on Ansible controller where built deb packages
# will be stored after fetching from build host.
securedrop_local_build: "../../build/{{ ansible_distribution_release }}/"

securedrop_generic_build_path: "/tmp/build/"

securedrop_app_rsync_opts:
  - "--chmod=u=rwX,g=rX,o=rX"
  - "--chown=root:root"
  - "--exclude=*.git"
  - "--exclude=*aths"
  - "--exclude=*.deb"
  - "--exclude=*.j2"
