---

- name: Configure apt-server
  hosts: aptservers
  become: yes
  tasks:
    - name: Establish QA strategy
      set_fact:
        QA_APTTEST: "{{ lookup('env','QA_APTTEST')|bool }}"

    - import_tasks: local_apt_mirror.yml
    - import_tasks: local_apt_with_debs.yml
      when: not QA_APTTEST

  vars:
    molecule_dir: "{{ lookup('env', 'MOLECULE_SCENARIO_DIRECTORY') }}"
    dpkg_dir: /var/repos/debs
    rep_component: main
    rep_arch: i386 amd64
    release_file: "/var/repos/base/dists/{{ rep_dist }}/Release"
    nginx_sites:
      default:
        - listen 80
        - root "/var/repos/base"
        - location / { autoindex on; }
        - location /gpg { alias /var/repos/base/; }
      encrypted:
        - listen 443 ssl
        - server_name apt.freedom.press
        - ssl_certificate /etc/ssl/certs/apt_freedom_press.pem
        - ssl_certificate_key /etc/ssl/private/apt_freedom_press.priv
        - root "/var/repos/base"
        - location / { {{ "proxy_pass https://apt-test.freedom.press;" if QA_APTTEST else "autoindex on;" }} }

- name: Configure apt-server
  hosts: securedrop
  gather_facts: false
  become: yes
  tasks:
    - block:
        - name: Redirect to local QA Apt server
          set_fact:
            apt_key_bits:
              - url: "http://{{ hostvars['apt']['ansible_eth0'].ipv4.address }}/gpg/apt-test.pub"
                id: 6D65484B
              - url: "http://{{ hostvars['apt']['ansible_eth0'].ipv4.address }}/gpg/apt-test-fpf.pub"
                id: 4A3BE4A92211B03C
            apt_test_etc_line: "{{ hostvars['apt']['ansible_eth0'].ipv4.address }}  apt.freedom.press"

        - name: Install testing apt key to keyring
          apt_key:
            id: "{{ item.id|default(omit) }}"
            url: "{{ item.url|default(omit) }}"
            data: "{{ item.data|default(omit) }}"
            state: present
          with_items: "{{ apt_key_bits }}"

        - name: Redirect apt.freedom.press to local apt server
          lineinfile:
            path: /etc/hosts
            regexp: apt.freedom.press$
            line: "{{ apt_test_etc_line }}"

        - name: Add apt-test CA to CA trusted store
          copy:
            src: cacert.pub
            dest: /usr/local/share/ca-certificates/fpf_test_ca.crt
          notify: update ca
      tags: apt

  handlers:
    - name: update ca
      command: update-ca-certificates
