---
- name: Read haveged defaults file to filter duplicate entries.
  command: awk '!a[$0]++' /etc/default/haveged
  register: haveged_defaults_no_duplicates_result
  # Read-only task, so don't perform change.
  # When writing to the file in a subsequent task,
  # the "changed" attribute will be honored (if appropriate).
  changed_when: false
  tags:
    - haveged
    - hardening

  # Previous Ansible tasks for managing /etc/default/haveged have
  # appended redundant lines to the file. To ensure idempotence,
  # we'll first remove any duplicate lines, then set the args
  # we want via `lineinfile` below.
- name: Remove duplicate entries from haveged defaults file.
  copy:
    dest: /etc/default/haveged
    # Appending newline is necessary for idempotence,
    # since the `lineinfile` task below will add it if not found.
    content: "{{ haveged_defaults_no_duplicates_result.stdout }}\n"
    owner: root
    group: root
    mode: "0644"
    backup: yes
  tags:
    - haveged
    - hardening

- name: Increase haveged's low entropy watermark to minimize "flag for reply" flow.
  lineinfile:
    dest: /etc/default/haveged
    regexp: '^DAEMON_ARGS'
    line: 'DAEMON_ARGS="-w 2400"'
  notify:
    - restart haveged
  tags:
    - haveged
    - hardening

# The following three tasks resolve haveged AppArmor issues on Xenial described in
# https://github.com/freedomofpress/securedrop/issues/4098.

- name: Check whether haveged AppArmor profile exists in expected location for Xenial.
  stat:
    path: "/etc/apparmor.d/usr.sbin.haveged"
  register: haveged_apparmor
  # Do not report changed, this task does not modify state.
  changed_when: false
  tags:
    - haveged
    - hardening

# This temporary fix ensures that the pid file haveged uses is whitelisted
# by AppArmor.
# Upstream bug: https://bugs.launchpad.net/ubuntu/+source/haveged/+bug/1708674
- name: Whitelist haveged pid file in its AppArmor profile.
  lineinfile:
    dest: /etc/apparmor.d/usr.sbin.haveged
    insertafter: "  #include <abstractions/base>"
    line: "  /run/haveged.pid rw,"
  when: haveged_apparmor.stat.exists
  tags:
    - haveged
    - hardening

# This temporary fix resolves a race condition where haveged would start
# prior to AppArmor, in which case haveged would be running unconfined.
# Bug described in: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=824179
- name: Start apparmor prior to haveged process.
  lineinfile:
    dest: /lib/systemd/system/haveged.service
    regexp: "^After=systemd-random-seed.service"
    line: "After=apparmor.service systemd-random-seed.service"
    backrefs: yes
  when: haveged_apparmor.stat.exists
  notify:
    - restart apparmor
    - restart haveged
  tags:
    - haveged
    - hardening
