---
- name: Mark GRUB2 as manually installed so its not removed.
  command: apt-mark manual grub-pc
  register: grubpc_manual_mark
  changed_when: "'grub-pc was already set to manually installed.' not in grubpc_manual_mark.stdout"
  tags:
    - apt
    - kernel
    - grub

- name: Clean old apt packages.
  command: apt-get -y autoremove
  register: apt_autoremove_all
  changed_when: "'The following packages will be REMOVED' in apt_autoremove_all.stdout"
  tags:
    - apt
